version: '3.8'

services:
  db_mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: homework1_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  # api:
  #   depends_on:
  #     - db_mysql
  #   build: 
  #     context: HW1
  #   restart:
  #     unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_APPLICATION_JSON: '{
  #       spring.datasource.url=jdbc:mysql://db_mysql:3306/homework1_db
  #       spring.datasource.username=user
  #       spring.datasource.password=password
  #       spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

  #       your.api.key=fca_live_9aY7p7AAwwpAbk6CHHmnFj4VAeTNwyBhJ0GGgst8

  #       spring.cache.type=redis
  #       spring.cache.redis.time-to-live=1800s
  #       }'

  init_mysql_db:
    depends_on:
      - db_mysql
    build:
      context: initdb

volumes:
  data:
    driver: local
