// package HW1;

// import static org.junit.jupiter.api.Assertions.assertEquals;

// import java.time.Duration;

// import org.junit.jupiter.api.BeforeEach;
// import org.junit.jupiter.api.Disabled;
// import org.junit.jupiter.api.Test;
// import org.junit.jupiter.api.extension.ExtendWith;
// import org.openqa.selenium.Dimension;
// import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.chrome.ChromeDriver;
// import org.openqa.selenium.firefox.FirefoxDriver;
// import org.openqa.selenium.support.ui.WebDriverWait;
// import org.openqa.selenium.support.ui.WebDriverWait;


// import HW1.pages.Index;
// import HW1.pages.TablePage;
// import io.github.bonigarcia.seljup.SeleniumJupiter;
// import org.openqa.selenium.support.ui.ExpectedConditions;


// @ExtendWith(SeleniumJupiter.class)
// public class SeleniumTest {

//     WebDriver driver;

//     @BeforeEach
//     public void setUp() {
//         driver = new ChromeDriver();
//     }

//     @Disabled
//     @Test
//     public void test(ChromeDriver driver) {
//         driver.get("http://localhost:8080/");

//         driver.manage().window().setSize(new Dimension(1550, 1001));

//         Index index = new Index(driver);
        
//         index.setFrom("São Pedro do Sul");
//         assertEquals("São Pedro do Sul", index.getFrom());

//         index.setTo("Aveiro");
//         assertEquals("Aveiro", index.getTo());

//         index.setDate("2024-04-12");
//         assertEquals("2024-04-12", index.getDate());

//         index.submitSearchForm();

//         TablePage tablePage = new TablePage(driver);
        
//         assertEquals("São Pedro do Sul", tablePage.getOriginText());
//         assertEquals("Aveiro", tablePage.getDestinationText());
//         assertEquals("2024-04-12", tablePage.getDateText());

//         tablePage.reserve();

//     }
// }

// // // Generated by Selenium IDE
// // import org.junit.Test;
// // import org.junit.Before;
// // import org.junit.After;
// // import static org.junit.Assert.*;
// // import static org.hamcrest.CoreMatchers.is;
// // import static org.hamcrest.core.IsNot.not;
// // import org.openqa.selenium.By;
// // import org.openqa.selenium.WebDriver;
// // import org.openqa.selenium.firefox.FirefoxDriver;
// // import org.openqa.selenium.chrome.ChromeDriver;
// // import org.openqa.selenium.remote.RemoteWebDriver;
// // import org.openqa.selenium.remote.DesiredCapabilities;
// // import org.openqa.selenium.Dimension;
// // import org.openqa.selenium.WebElement;
// // import org.openqa.selenium.interactions.Actions;
// // import org.openqa.selenium.support.ui.ExpectedConditions;
// // import org.openqa.selenium.support.ui.WebDriverWait;
// // import org.openqa.selenium.JavascriptExecutor;
// // import org.openqa.selenium.Alert;
// // import org.openqa.selenium.Keys;
// // import java.util.*;
// // import java.net.MalformedURLException;
// // import java.net.URL;
// // public class TesteTest {
// //   private WebDriver driver;
// //   private Map<String, Object> vars;
// //   JavascriptExecutor js;
// //   @Before
// //   public void setUp() {
// //     driver = new ChromeDriver();
// //     js = (JavascriptExecutor) driver;
// //     vars = new HashMap<String, Object>();
// //   }
// //   @After
// //   public void tearDown() {
// //     driver.quit();
// //   }
// //   @Test
// //   public void teste() {
// //     driver.get("http://localhost:8080/");
// //     driver.manage().window().setSize(new Dimension(1920, 976));
// //     driver.findElement(By.id("from")).click();
// //     driver.findElement(By.id("from")).sendKeys("São Pedro do Sul");
// //     driver.findElement(By.id("to")).click();
// //     driver.findElement(By.id("to")).sendKeys("Aveiro");
// //     driver.findElement(By.id("date")).click();
// //     driver.findElement(By.id("date")).sendKeys("2024-04-12");
// //     driver.findElement(By.cssSelector("button:nth-child(7)")).click();
// //     {
// //       WebElement dropdown = driver.findElement(By.id("currencySelector"));
// //       dropdown.findElement(By.xpath("//option[. = 'USD - US Dollar']")).click();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).clickAndHold().perform();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).perform();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).release().perform();
// //     }
// //     {
// //       WebElement dropdown = driver.findElement(By.id("currencySelector"));
// //       dropdown.findElement(By.xpath("//option[. = 'EUR - Euro']")).click();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).clickAndHold().perform();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).perform();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).release().perform();
// //     }
// //     {
// //       WebElement dropdown = driver.findElement(By.id("currencySelector"));
// //       dropdown.findElement(By.xpath("//option[. = 'USD - US Dollar']")).click();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).clickAndHold().perform();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).perform();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).release().perform();
// //     }
// //     {
// //       WebElement dropdown = driver.findElement(By.id("currencySelector"));
// //       dropdown.findElement(By.xpath("//option[. = 'EUR - Euro']")).click();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).clickAndHold().perform();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).perform();
// //     }
// //     {
// //       WebElement element = driver.findElement(By.id("currencySelector"));
// //       Actions builder = new Actions(driver);
// //       builder.moveToElement(element).release().perform();
// //     }
// //     driver.findElement(By.cssSelector("button")).click();
// //     driver.findElement(By.name("name")).click();
// //     driver.findElement(By.name("name")).sendKeys("Sara");
// //     driver.findElement(By.name("surname")).click();
// //     driver.findElement(By.name("surname")).sendKeys("Almeida");
// //     driver.findElement(By.name("email")).click();
// //     driver.findElement(By.name("email")).sendKeys("sarafalmeida@ua.pt");
// //     driver.findElement(By.name("phoneNumber")).click();
// //     driver.findElement(By.name("phoneNumber")).sendKeys("123456789");
// //     driver.findElement(By.name("address")).click();
// //     driver.findElement(By.name("address")).sendKeys("Rua da Alegria");
// //     driver.findElement(By.name("city")).click();
// //     driver.findElement(By.name("city")).sendKeys("Viseu");
// //     driver.findElement(By.name("postalCode")).click();
// //     driver.findElement(By.name("postalCode")).sendKeys("3660-231");
// //     driver.findElement(By.name("country")).click();
// //     driver.findElement(By.name("country")).sendKeys("Portugal");
// //     driver.findElement(By.name("creditCardNumber")).click();
// //     driver.findElement(By.name("creditCardNumber")).click();
// //     driver.findElement(By.name("creditCardNumber")).sendKeys("21312332534653");
// //     driver.findElement(By.name("creditCardMM")).click();
// //     driver.findElement(By.name("creditCardMM")).sendKeys("12");
// //     driver.findElement(By.name("creditCardYY")).click();
// //     driver.findElement(By.name("creditCardYY")).sendKeys("26");
// //     driver.findElement(By.name("creditCardCVV")).click();
// //     driver.findElement(By.name("creditCardCVV")).sendKeys("123");
// //     driver.findElement(By.cssSelector(".btn:nth-child(29)")).click();
// //     driver.findElement(By.cssSelector("p")).click();
// //     driver.findElement(By.cssSelector("button")).click();
// //     driver.findElement(By.id("tokenInputField")).click();
// //     driver.findElement(By.id("tokenInputField")).sendKeys("3cd37035-a8af-4050-a06d-ed188ba54d69");
// //     driver.findElement(By.cssSelector("button")).click();
// //     driver.findElement(By.id("tokenInputField")).click();
// //     driver.findElement(By.id("tokenInputField")).sendKeys("3cd37035-a8af-4050-a06d-ed188ba54d60");
// //     driver.findElement(By.cssSelector("button")).click();
// //   }
// // }